name: Build Allure Report

on: 
  workflow_dispatch:
  push: 
    branches:
      - master

jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: List Directory
        run: |
          ls -la
          echo "Testing workflow execution"
